version: '3'
services:
  spring-boot-app:
    build:
      context: .  # Используем текущий каталог, где находится Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Проксируем порт 8080 для приложения Spring Boot
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/fake-twitter
    networks:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    networks:
      - backend

networks:
  backend:
