server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    mongodb:
      uri: mongodb://localhost:27017/fake-twitter